name: Tagtest
on: push

jobs:
  build-n-publish:
    name: Testing tagging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Describe no tag (all tags)
      run: |
        git describe --all --tags
    - name: Describe with tag (all tags)
      if: startsWith(github.ref, 'refs/tags')
      run: |
        git describe --all --tags

    - name: Describe no tag (tags)
      run: |
        git describe --tags
    - name: Describe with tag (tags)
      if: startsWith(github.ref, 'refs/tags')
      run: |
        git describe --tags

    - name: Describe no tag
      continue-on-error: true
      run: |
        git describe
    - name: Describe with tag
      continue-on-error: true
      if: startsWith(github.ref, 'refs/tags')
      run: |
        git describe